const REPLACEMENTS: Array<[RegExp, string]> = [
  [new RegExp("\\\\big{\\)}", 'g'), "\\\\big)"],
  [new RegExp("\\\\big{\\(}", 'g'), "\\\\big("],
  [new RegExp("\\\\big {\\)}", 'g'), "\\\\big)"],
  [new RegExp("\\\\big {\\(}", 'g'), "\\\\big("],
  [new RegExp("\\\\bigr{\\)}", 'g'), "\\\\bigr)"],
  [new RegExp("\\\\bigr{\\(}", 'g'), "\\\\bigr("],
  [new RegExp("\\\\bigr {\\)}", 'g'), "\\\\bigr)"],
  [new RegExp("\\\\bigr {\\(}", 'g'), "\\\\bigr("],
  [new RegExp("\\\\bigm{\\)}", 'g'), "\\\\bigm)"],
  [new RegExp("\\\\bigm{\\(}", 'g'), "\\\\bigm("],
  [new RegExp("\\\\bigm {\\)}", 'g'), "\\\\bigm)"],
  [new RegExp("\\\\bigm {\\(}", 'g'), "\\\\bigm("],
  [new RegExp("\\\\bigl{\\)}", 'g'), "\\\\bigl)"],
  [new RegExp("\\\\bigl{\\(}", 'g'), "\\\\bigl("],
  [new RegExp("\\\\bigl {\\)}", 'g'), "\\\\bigl)"],
  [new RegExp("\\\\bigl {\\(}", 'g'), "\\\\bigl("],
  [new RegExp("\\\\bigg{\\)}", 'g'), "\\\\bigg)"],
  [new RegExp("\\\\bigg{\\(}", 'g'), "\\\\bigg("],
  [new RegExp("\\\\bigg {\\)}", 'g'), "\\\\bigg)"],
  [new RegExp("\\\\bigg {\\(}", 'g'), "\\\\bigg("],
  [new RegExp("\\\\biggr{\\)}", 'g'), "\\\\biggr)"],
  [new RegExp("\\\\biggr{\\(}", 'g'), "\\\\biggr("],
  [new RegExp("\\\\biggr {\\)}", 'g'), "\\\\biggr)"],
  [new RegExp("\\\\biggr {\\(}", 'g'), "\\\\biggr("],
  [new RegExp("\\\\biggm{\\)}", 'g'), "\\\\biggm)"],
  [new RegExp("\\\\biggm{\\(}", 'g'), "\\\\biggm("],
  [new RegExp("\\\\biggm {\\)}", 'g'), "\\\\biggm)"],
  [new RegExp("\\\\biggm {\\(}", 'g'), "\\\\biggm("],
  [new RegExp("\\\\biggl{\\)}", 'g'), "\\\\biggl)"],
  [new RegExp("\\\\biggl{\\(}", 'g'), "\\\\biggl("],
  [new RegExp("\\\\biggl {\\)}", 'g'), "\\\\biggl)"],
  [new RegExp("\\\\biggl {\\(}", 'g'), "\\\\biggl("],
  [new RegExp("\\\\Big{\\)}", 'g'), "\\\\Big)"],
  [new RegExp("\\\\Big{\\(}", 'g'), "\\\\Big("],
  [new RegExp("\\\\Big {\\)}", 'g'), "\\\\Big)"],
  [new RegExp("\\\\Big {\\(}", 'g'), "\\\\Big("],
  [new RegExp("\\\\Bigr{\\)}", 'g'), "\\\\Bigr)"],
  [new RegExp("\\\\Bigr{\\(}", 'g'), "\\\\Bigr("],
  [new RegExp("\\\\Bigr {\\)}", 'g'), "\\\\Bigr)"],
  [new RegExp("\\\\Bigr {\\(}", 'g'), "\\\\Bigr("],
  [new RegExp("\\\\Bigm{\\)}", 'g'), "\\\\Bigm)"],
  [new RegExp("\\\\Bigm{\\(}", 'g'), "\\\\Bigm("],
  [new RegExp("\\\\Bigm {\\)}", 'g'), "\\\\Bigm)"],
  [new RegExp("\\\\Bigm {\\(}", 'g'), "\\\\Bigm("],
  [new RegExp("\\\\Bigl{\\)}", 'g'), "\\\\Bigl)"],
  [new RegExp("\\\\Bigl{\\(}", 'g'), "\\\\Bigl("],
  [new RegExp("\\\\Bigl {\\)}", 'g'), "\\\\Bigl)"],
  [new RegExp("\\\\Bigl {\\(}", 'g'), "\\\\Bigl("],
  [new RegExp("\\\\Bigg{\\)}", 'g'), "\\\\Bigg)"],
  [new RegExp("\\\\Bigg{\\(}", 'g'), "\\\\Bigg("],
  [new RegExp("\\\\Bigg {\\)}", 'g'), "\\\\Bigg)"],
  [new RegExp("\\\\Bigg {\\(}", 'g'), "\\\\Bigg("],
  [new RegExp("\\\\Biggr{\\)}", 'g'), "\\\\Biggr)"],
  [new RegExp("\\\\Biggr{\\(}", 'g'), "\\\\Biggr("],
  [new RegExp("\\\\Biggr {\\)}", 'g'), "\\\\Biggr)"],
  [new RegExp("\\\\Biggr {\\(}", 'g'), "\\\\Biggr("],
  [new RegExp("\\\\Biggm{\\)}", 'g'), "\\\\Biggm)"],
  [new RegExp("\\\\Biggm{\\(}", 'g'), "\\\\Biggm("],
  [new RegExp("\\\\Biggm {\\)}", 'g'), "\\\\Biggm)"],
  [new RegExp("\\\\Biggm {\\(}", 'g'), "\\\\Biggm("],
  [new RegExp("\\\\Biggl{\\)}", 'g'), "\\\\Biggl)"],
  [new RegExp("\\\\Biggl{\\(}", 'g'), "\\\\Biggl("],
  [new RegExp("\\\\Biggl {\\)}", 'g'), "\\\\Biggl)"],
  [new RegExp("\\\\Biggl {\\(}", 'g'), "\\\\Biggl("],
  [new RegExp("\\\\big\\{\\\\\\}\\}", 'g'), "\\\\big\\\\}"],
  [new RegExp("\\\\big\\{\\\\\\{\\}", 'g'), "\\\\big\\\\{"],
  [new RegExp("\\\\big \\{\\\\\\}\\}", 'g'), "\\\\big\\\\}"],
  [new RegExp("\\\\big \\{\\\\\\{\\}", 'g'), "\\\\big\\\\{"],
  [new RegExp("\\\\bigr\\{\\\\\\}\\}", 'g'), "\\\\bigr\\\\}"],
  [new RegExp("\\\\bigr\\{\\\\\\{\\}", 'g'), "\\\\bigr\\\\{"],
  [new RegExp("\\\\bigr \\{\\\\\\}\\}", 'g'), "\\\\bigr\\\\}"],
  [new RegExp("\\\\bigr \\{\\\\\\{\\}", 'g'), "\\\\bigr\\\\{"],
  [new RegExp("\\\\bigm\\{\\\\\\}\\}", 'g'), "\\\\bigm\\\\}"],
  [new RegExp("\\\\bigm\\{\\\\\\{\\}", 'g'), "\\\\bigm\\\\{"],
  [new RegExp("\\\\bigm \\{\\\\\\}\\}", 'g'), "\\\\bigm\\\\}"],
  [new RegExp("\\\\bigm \\{\\\\\\{\\}", 'g'), "\\\\bigm\\\\{"],
  [new RegExp("\\\\bigl\\{\\\\\\}\\}", 'g'), "\\\\bigl\\\\}"],
  [new RegExp("\\\\bigl\\{\\\\\\{\\}", 'g'), "\\\\bigl\\\\{"],
  [new RegExp("\\\\bigl \\{\\\\\\}\\}", 'g'), "\\\\bigl\\\\}"],
  [new RegExp("\\\\bigl \\{\\\\\\{\\}", 'g'), "\\\\bigl\\\\{"],
  [new RegExp("\\\\bigg\\{\\\\\\}\\}", 'g'), "\\\\bigg\\\\}"],
  [new RegExp("\\\\bigg\\{\\\\\\{\\}", 'g'), "\\\\bigg\\\\{"],
  [new RegExp("\\\\bigg \\{\\\\\\}\\}", 'g'), "\\\\bigg\\\\}"],
  [new RegExp("\\\\bigg \\{\\\\\\{\\}", 'g'), "\\\\bigg\\\\{"],
  [new RegExp("\\\\biggr\\{\\\\\\}\\}", 'g'), "\\\\biggr\\\\}"],
  [new RegExp("\\\\biggr\\{\\\\\\{\\}", 'g'), "\\\\biggr\\\\{"],
  [new RegExp("\\\\biggr \\{\\\\\\}\\}", 'g'), "\\\\biggr\\\\}"],
  [new RegExp("\\\\biggr \\{\\\\\\{\\}", 'g'), "\\\\biggr\\\\{"],
  [new RegExp("\\\\biggm\\{\\\\\\}\\}", 'g'), "\\\\biggm\\\\}"],
  [new RegExp("\\\\biggm\\{\\\\\\{\\}", 'g'), "\\\\biggm\\\\{"],
  [new RegExp("\\\\biggm \\{\\\\\\}\\}", 'g'), "\\\\biggm\\\\}"],
  [new RegExp("\\\\biggm \\{\\\\\\{\\}", 'g'), "\\\\biggm\\\\{"],
  [new RegExp("\\\\biggl\\{\\\\\\}\\}", 'g'), "\\\\biggl\\\\}"],
  [new RegExp("\\\\biggl\\{\\\\\\{\\}", 'g'), "\\\\biggl\\\\{"],
  [new RegExp("\\\\biggl \\{\\\\\\}\\}", 'g'), "\\\\biggl\\\\}"],
  [new RegExp("\\\\biggl \\{\\\\\\{\\}", 'g'), "\\\\biggl\\\\{"],
  [new RegExp("\\\\Big\\{\\\\\\}\\}", 'g'), "\\\\Big\\\\}"],
  [new RegExp("\\\\Big\\{\\\\\\{\\}", 'g'), "\\\\Big\\\\{"],
  [new RegExp("\\\\Big \\{\\\\\\}\\}", 'g'), "\\\\Big\\\\}"],
  [new RegExp("\\\\Big \\{\\\\\\{\\}", 'g'), "\\\\Big\\\\{"],
  [new RegExp("\\\\Bigr\\{\\\\\\}\\}", 'g'), "\\\\Bigr\\\\}"],
  [new RegExp("\\\\Bigr\\{\\\\\\{\\}", 'g'), "\\\\Bigr\\\\{"],
  [new RegExp("\\\\Bigr \\{\\\\\\}\\}", 'g'), "\\\\Bigr\\\\}"],
  [new RegExp("\\\\Bigr \\{\\\\\\{\\}", 'g'), "\\\\Bigr\\\\{"],
  [new RegExp("\\\\Bigm\\{\\\\\\}\\}", 'g'), "\\\\Bigm\\\\}"],
  [new RegExp("\\\\Bigm\\{\\\\\\{\\}", 'g'), "\\\\Bigm\\\\{"],
  [new RegExp("\\\\Bigm \\{\\\\\\}\\}", 'g'), "\\\\Bigm\\\\}"],
  [new RegExp("\\\\Bigm \\{\\\\\\{\\}", 'g'), "\\\\Bigm\\\\{"],
  [new RegExp("\\\\Bigl\\{\\\\\\}\\}", 'g'), "\\\\Bigl\\\\}"],
  [new RegExp("\\\\Bigl\\{\\\\\\{\\}", 'g'), "\\\\Bigl\\\\{"],
  [new RegExp("\\\\Bigl \\{\\\\\\}\\}", 'g'), "\\\\Bigl\\\\}"],
  [new RegExp("\\\\Bigl \\{\\\\\\{\\}", 'g'), "\\\\Bigl\\\\{"],
  [new RegExp("\\\\Bigg\\{\\\\\\}\\}", 'g'), "\\\\Bigg\\\\}"],
  [new RegExp("\\\\Bigg\\{\\\\\\{\\}", 'g'), "\\\\Bigg\\\\{"],
  [new RegExp("\\\\Bigg \\{\\\\\\}\\}", 'g'), "\\\\Bigg\\\\}"],
  [new RegExp("\\\\Bigg \\{\\\\\\{\\}", 'g'), "\\\\Bigg\\\\{"],
  [new RegExp("\\\\Biggr\\{\\\\\\}\\}", 'g'), "\\\\Biggr\\\\}"],
  [new RegExp("\\\\Biggr\\{\\\\\\{\\}", 'g'), "\\\\Biggr\\\\{"],
  [new RegExp("\\\\Biggr \\{\\\\\\}\\}", 'g'), "\\\\Biggr\\\\}"],
  [new RegExp("\\\\Biggr \\{\\\\\\{\\}", 'g'), "\\\\Biggr\\\\{"],
  [new RegExp("\\\\Biggl\\{\\\\\\}\\}", 'g'), "\\\\Biggl\\\\}"],
  [new RegExp("\\\\Biggl\\{\\\\\\{\\}", 'g'), "\\\\Biggl\\\\{"],
  [new RegExp("\\\\Biggl \\{\\\\\\}\\}", 'g'), "\\\\Biggl\\\\}"],
  [new RegExp("\\\\Biggl \\{\\\\\\{\\}", 'g'), "\\\\Biggl\\\\{"],
  [new RegExp("\\\\big\\{\\|\\}", 'g'), "\\\\big|"],
  [new RegExp("\\\\Big\\{\\|\\}", 'g'), "\\\\Big|"],
  [new RegExp("\\\\big \\{\\|\\}", 'g'), "\\\\big|"],
  [new RegExp("\\\\Big \\{\\|\\}", 'g'), "\\\\Big|"],
  [new RegExp("\\\\bigm\\{\\|\\}", 'g'), "\\\\bigm|"],
  [new RegExp("\\\\Bigm\\{\\|\\}", 'g'), "\\\\Bigm|"],
  [new RegExp("\\\\bigm \\{\\|\\}", 'g'), "\\\\bigm|"],
  [new RegExp("\\\\Bigm \\{\\|\\}", 'g'), "\\\\Bigm|"],
  [new RegExp("\\\\bigr\\{\\|\\}", 'g'), "\\\\bigr|"],
  [new RegExp("\\\\Bigr\\{\\|\\}", 'g'), "\\\\Bigr|"],
  [new RegExp("\\\\bigr \\{\\|\\}", 'g'), "\\\\bigr|"],
  [new RegExp("\\\\Bigr \\{\\|\\}", 'g'), "\\\\Bigr|"],
  [new RegExp("\\\\bigl\\{\\|\\}", 'g'), "\\\\bigl|"],
  [new RegExp("\\\\Bigl\\{\\|\\}", 'g'), "\\\\Bigl|"],
  [new RegExp("\\\\bigl \\{\\|\\}", 'g'), "\\\\bigl|"],
  [new RegExp("\\\\Bigl \\{\\|\\}", 'g'), "\\\\Bigl|"],
  [new RegExp("\\\\bigg\\{\\|\\}", 'g'), "\\\\bigg|"],
  [new RegExp("\\\\Bigg\\{\\|\\}", 'g'), "\\\\Bigg|"],
  [new RegExp("\\\\bigg \\{\\|\\}", 'g'), "\\\\bigg|"],
  [new RegExp("\\\\Bigg \\{\\|\\}", 'g'), "\\\\Bigg|"],
  [new RegExp("\\\\biggr\\{\\|\\}", 'g'), "\\\\biggr|"],
  [new RegExp("\\\\Biggr\\{\\|\\}", 'g'), "\\\\Biggr|"],
  [new RegExp("\\\\biggr \\{\\|\\}", 'g'), "\\\\biggr|"],
  [new RegExp("\\\\Biggr \\{\\|\\}", 'g'), "\\\\Biggr|"],
  [new RegExp("\\\\biggm\\{\\|\\}", 'g'), "\\\\biggm|"],
  [new RegExp("\\\\Biggm\\{\\|\\}", 'g'), "\\\\Biggm|"],
  [new RegExp("\\\\biggm \\{\\|\\}", 'g'), "\\\\biggm|"],
  [new RegExp("\\\\Biggm \\{\\|\\}", 'g'), "\\\\Biggm|"],
  [new RegExp("\\\\biggl\\{\\|\\}", 'g'), "\\\\biggl|"],
  [new RegExp("\\\\Biggl\\{\\|\\}", 'g'), "\\\\Biggl|"],
  [new RegExp("\\\\biggl \\{\\|\\}", 'g'), "\\\\biggl|"],
  [new RegExp("\\\\Biggl \\{\\|\\}", 'g'), "\\\\Biggl|"],
  [new RegExp("\\\\big\\{\\\\\\|\\}", 'g'), "\\\\big\\\\|"],
  [new RegExp("\\\\Big\\{\\\\\\|\\}", 'g'), "\\\\Big\\\\|"],
  [new RegExp("\\\\big \\{\\\\\\|\\}", 'g'), "\\\\big\\\\|"],
  [new RegExp("\\\\Big \\{\\\\\\|\\}", 'g'), "\\\\Big\\\\|"],
  [new RegExp("\\\\bigm\\{\\\\\\|\\}", 'g'), "\\\\bigm\\\\|"],
  [new RegExp("\\\\Bigm\\{\\\\\\|\\}", 'g'), "\\\\Bigm\\\\|"],
  [new RegExp("\\\\bigm \\{\\\\\\|\\}", 'g'), "\\\\bigm\\\\|"],
  [new RegExp("\\\\Bigm \\{\\\\\\|\\}", 'g'), "\\\\Bigm\\\\|"],
  [new RegExp("\\\\bigr\\{\\\\\\|\\}", 'g'), "\\\\bigr\\\\|"],
  [new RegExp("\\\\Bigr\\{\\\\\\|\\}", 'g'), "\\\\Bigr\\\\|"],
  [new RegExp("\\\\bigr \\{\\\\\\|\\}", 'g'), "\\\\bigr\\\\|"],
  [new RegExp("\\\\Bigr \\{\\\\\\|\\}", 'g'), "\\\\Bigr\\\\|"],
  [new RegExp("\\\\bigl\\{\\\\\\|\\}", 'g'), "\\\\bigl\\\\|"],
  [new RegExp("\\\\Bigl\\{\\\\\\|\\}", 'g'), "\\\\Bigl\\\\|"],
  [new RegExp("\\\\bigl \\{\\\\\\|\\}", 'g'), "\\\\bigl\\\\|"],
  [new RegExp("\\\\Bigl \\{\\\\\\|\\}", 'g'), "\\\\Bigl\\\\|"],
  [new RegExp("\\\\bigg\\{\\\\\\|\\}", 'g'), "\\\\bigg\\\\|"],
  [new RegExp("\\\\Bigg\\{\\\\\\|\\}", 'g'), "\\\\Bigg\\\\|"],
  [new RegExp("\\\\bigg \\{\\\\\\|\\}", 'g'), "\\\\bigg\\\\|"],
  [new RegExp("\\\\Bigg \\{\\\\\\|\\}", 'g'), "\\\\Bigg\\\\|"],
  [new RegExp("\\\\biggr\\{\\\\\\|\\}", 'g'), "\\\\biggr\\\\|"],
  [new RegExp("\\\\Biggr\\{\\\\\\|\\}", 'g'), "\\\\Biggr\\\\|"],
  [new RegExp("\\\\biggr \\{\\\\\\|\\}", 'g'), "\\\\biggr\\\\|"],
  [new RegExp("\\\\Biggr \\{\\\\\\|\\}", 'g'), "\\\\Biggr\\\\|"],
  [new RegExp("\\\\biggm\\{\\\\\\|\\}", 'g'), "\\\\biggm\\\\|"],
  [new RegExp("\\\\Biggm\\{\\\\\\|\\}", 'g'), "\\\\Biggm\\\\|"],
  [new RegExp("\\\\biggm \\{\\\\\\|\\}", 'g'), "\\\\biggm\\\\|"],
  [new RegExp("\\\\Biggm \\{\\\\\\|\\}", 'g'), "\\\\Biggm\\\\|"],
  [new RegExp("\\\\biggl\\{\\\\\\|\\}", 'g'), "\\\\biggl\\\\|"],
  [new RegExp("\\\\Biggl\\{\\\\\\|\\}", 'g'), "\\\\Biggl\\\\|"],
  [new RegExp("\\\\biggl \\{\\\\\\|\\}", 'g'), "\\\\biggl\\\\|"],
  [new RegExp("\\\\Biggl \\{\\\\\\|\\}", 'g'), "\\\\Biggl\\\\|"],
  [new RegExp("\\\\big\\{\\]\\}", 'g'), "\\\\big]"],
  [new RegExp("\\\\Big\\{\\]\\}", 'g'), "\\\\Big]"],
  [new RegExp("\\\\big \\{\\]\\}", 'g'), "\\\\big]"],
  [new RegExp("\\\\Big \\{\\]\\}", 'g'), "\\\\Big]"],
  [new RegExp("\\\\big\\{\\[\\}", 'g'), "\\\\big["],
  [new RegExp("\\\\Big\\{\\[\\}", 'g'), "\\\\Big["],
  [new RegExp("\\\\big \\{\\[\\}", 'g'), "\\\\big["],
  [new RegExp("\\\\Big \\{\\[\\}", 'g'), "\\\\Big["],
  [new RegExp("\\\\bigm\\{\\]\\}", 'g'), "\\\\bigm]"],
  [new RegExp("\\\\Bigm\\{\\]\\}", 'g'), "\\\\Bigm]"],
  [new RegExp("\\\\bigm \\{\\]\\}", 'g'), "\\\\bigm]"],
  [new RegExp("\\\\Bigm \\{\\]\\}", 'g'), "\\\\Bigm]"],
  [new RegExp("\\\\bigm\\{\\[\\}", 'g'), "\\\\bigm["],
  [new RegExp("\\\\Bigm\\{\\[\\}", 'g'), "\\\\Bigm["],
  [new RegExp("\\\\bigm \\{\\[\\}", 'g'), "\\\\bigm["],
  [new RegExp("\\\\Bigm \\{\\[\\}", 'g'), "\\\\Bigm["],
  [new RegExp("\\\\bigr\\{\\]\\}", 'g'), "\\\\bigr]"],
  [new RegExp("\\\\Bigr\\{\\]\\}", 'g'), "\\\\Bigr]"],
  [new RegExp("\\\\bigr \\{\\]\\}", 'g'), "\\\\bigr]"],
  [new RegExp("\\\\Bigr \\{\\]\\}", 'g'), "\\\\Bigr]"],
  [new RegExp("\\\\bigr\\{\\[\\}", 'g'), "\\\\bigr["],
  [new RegExp("\\\\Bigr\\{\\[\\}", 'g'), "\\\\Bigr["],
  [new RegExp("\\\\bigr \\{\\[\\}", 'g'), "\\\\bigr["],
  [new RegExp("\\\\Bigr \\{\\[\\}", 'g'), "\\\\Bigr["],
  [new RegExp("\\\\bigl\\{\\]\\}", 'g'), "\\\\bigl]"],
  [new RegExp("\\\\Bigl\\{\\]\\}", 'g'), "\\\\Bigl]"],
  [new RegExp("\\\\bigl \\{\\]\\}", 'g'), "\\\\bigl]"],
  [new RegExp("\\\\Bigl \\{\\]\\}", 'g'), "\\\\Bigl]"],
  [new RegExp("\\\\bigl\\{\\[\\}", 'g'), "\\\\bigl["],
  [new RegExp("\\\\Bigl\\{\\[\\}", 'g'), "\\\\Bigl["],
  [new RegExp("\\\\bigl \\{\\[\\}", 'g'), "\\\\bigl["],
  [new RegExp("\\\\Bigl \\{\\[\\}", 'g'), "\\\\Bigl["],
  [new RegExp("\\\\bigg\\{\\]\\}", 'g'), "\\\\bigg]"],
  [new RegExp("\\\\Bigg\\{\\]\\}", 'g'), "\\\\Bigg]"],
  [new RegExp("\\\\bigg \\{\\]\\}", 'g'), "\\\\bigg]"],
  [new RegExp("\\\\Bigg \\{\\]\\}", 'g'), "\\\\Bigg]"],
  [new RegExp("\\\\bigg\\{\\[\\}", 'g'), "\\\\bigg["],
  [new RegExp("\\\\Bigg\\{\\[\\}", 'g'), "\\\\Bigg["],
  [new RegExp("\\\\bigg \\{\\[\\}", 'g'), "\\\\bigg["],
  [new RegExp("\\\\Bigg \\{\\[\\}", 'g'), "\\\\Bigg["],
  [new RegExp("\\\\biggr\\{\\]\\}", 'g'), "\\\\biggr]"],
  [new RegExp("\\\\Biggr\\{\\]\\}", 'g'), "\\\\Biggr]"],
  [new RegExp("\\\\biggr \\{\\]\\}", 'g'), "\\\\biggr]"],
  [new RegExp("\\\\Biggr \\{\\]\\}", 'g'), "\\\\Biggr]"],
  [new RegExp("\\\\biggr\\{\\[\\}", 'g'), "\\\\biggr["],
  [new RegExp("\\\\Biggr\\{\\[\\}", 'g'), "\\\\Biggr["],
  [new RegExp("\\\\biggr \\{\\[\\}", 'g'), "\\\\biggr["],
  [new RegExp("\\\\Biggr \\{\\[\\}", 'g'), "\\\\Biggr["],
  [new RegExp("\\\\biggm{\\[}", 'g'), "\\\\biggm\\["],
  [new RegExp("\\\\Biggm{\\[}", 'g'), "\\\\Biggm\\["],
  [new RegExp("\\\\biggm {\\[}", 'g'), "\\\\biggm\\["],
  [new RegExp("\\\\Biggm {\\[}", 'g'), "\\\\Biggm\\["],
  [new RegExp("\\\\biggm\\{\\]\\}", 'g'), "\\\\biggm\\]"],
  [new RegExp("\\\\Biggm\\{\\]\\}", 'g'), "\\\\Biggm\\]"],
  [new RegExp("\\\\biggm \\{\\]\\}", 'g'), "\\\\biggm\\]"],
  [new RegExp("\\\\Biggm \\{\\]\\}", 'g'), "\\\\Biggm\\]"],
  [new RegExp("\\\\biggl\\{\\[\\}", 'g'), "\\\\biggl\\["],
  [new RegExp("\\\\Biggl\\{\\[\\}", 'g'), "\\\\Biggl\\["],
  [new RegExp("\\\\biggl \\{\\[\\}", 'g'), "\\\\biggl\\["],
  [new RegExp("\\\\Biggl \\{\\[\\}", 'g'), "\\\\Biggl\\["],
  [new RegExp("\\\\biggl\\{\\]\\}", 'g'), "\\\\biggl\\]"],
  [new RegExp("\\\\Biggl\\{\\]\\}", 'g'), "\\\\Biggl\\]"],
  [new RegExp("\\\\biggl \\{\\]\\}", 'g'), "\\\\biggl\\]"],
  [new RegExp("\\\\Biggl \\{\\]\\}", 'g'), "\\\\Biggl\\]"],
  [new RegExp("\\\\big\\{\\\\rangle\\}", 'g'), "\\\\big\\\\rangle "],
  [new RegExp("\\\\big\\{\\\\langle\\}", 'g'), "\\\\big\\\\langle "],
  [new RegExp("\\\\big \\{\\\\rangle\\}", 'g'), "\\\\big\\\\rangle "],
  [new RegExp("\\\\big \\{\\\\langle\\}", 'g'), "\\\\big\\\\langle "],
  [new RegExp("\\\\bigr\\{\\\\rangle\\}", 'g'), "\\\\bigr\\\\rangle "],
  [new RegExp("\\\\bigr\\{\\\\langle\\}", 'g'), "\\\\bigr\\\\langle "],
  [new RegExp("\\\\bigr \\{\\\\rangle\\}", 'g'), "\\\\bigr\\\\rangle "],
  [new RegExp("\\\\bigr \\{\\\\langle\\}", 'g'), "\\\\bigr\\\\langle "],
  [new RegExp("\\\\bigm\\{\\\\rangle\\}", 'g'), "\\\\bigm\\\\rangle "],
  [new RegExp("\\\\bigm\\{\\\\langle\\}", 'g'), "\\\\bigm\\\\langle "],
  [new RegExp("\\\\bigm \\{\\\\rangle\\}", 'g'), "\\\\bigm\\\\rangle "],
  [new RegExp("\\\\bigm \\{\\\\langle\\}", 'g'), "\\\\bigm\\\\langle "],
  [new RegExp("\\\\bigl\\{\\\\rangle\\}", 'g'), "\\\\bigl\\\\rangle "],
  [new RegExp("\\\\bigl\\{\\\\langle\\}", 'g'), "\\\\bigl\\\\langle "],
  [new RegExp("\\\\bigl \\{\\\\rangle\\}", 'g'), "\\\\bigl\\\\rangle "],
  [new RegExp("\\\\bigl \\{\\\\langle\\}", 'g'), "\\\\bigl\\\\langle "],
  [new RegExp("\\\\bigg\\{\\\\rangle\\}", 'g'), "\\\\bigg\\\\rangle "],
  [new RegExp("\\\\bigg\\{\\\\langle\\}", 'g'), "\\\\bigg\\\\langle "],
  [new RegExp("\\\\bigg \\{\\\\rangle\\}", 'g'), "\\\\bigg\\\\rangle "],
  [new RegExp("\\\\bigg \\{\\\\langle\\}", 'g'), "\\\\bigg\\\\langle "],
  [new RegExp("\\\\biggr\\{\\\\rangle\\}", 'g'), "\\\\biggr\\\\rangle "],
  [new RegExp("\\\\biggr\\{\\\\langle\\}", 'g'), "\\\\biggr\\\\langle "],
  [new RegExp("\\\\biggr \\{\\\\rangle\\}", 'g'), "\\\\biggr\\\\rangle "],
  [new RegExp("\\\\biggr \\{\\\\langle\\}", 'g'), "\\\\biggr\\\\langle "],
  [new RegExp("\\\\biggm\\{\\\\rangle\\}", 'g'), "\\\\biggm\\\\rangle "],
  [new RegExp("\\\\biggm\\{\\\\langle\\}", 'g'), "\\\\biggm\\\\langle "],
  [new RegExp("\\\\biggm \\{\\\\rangle\\}", 'g'), "\\\\biggm\\\\rangle "],
  [new RegExp("\\\\biggm \\{\\\\langle\\}", 'g'), "\\\\biggm\\\\langle "],
  [new RegExp("\\\\biggl\\{\\\\rangle\\}", 'g'), "\\\\biggl\\\\rangle "],
  [new RegExp("\\\\biggl\\{\\\\langle\\}", 'g'), "\\\\biggl\\\\langle "],
  [new RegExp("\\\\biggl \\{\\\\rangle\\}", 'g'), "\\\\biggl\\\\rangle "],
  [new RegExp("\\\\biggl \\{\\\\langle\\}", 'g'), "\\\\biggl\\\\langle "],
  [new RegExp("\\\\Big\\{\\\\rangle\\}", 'g'), "\\\\Big\\\\rangle "],
  [new RegExp("\\\\Big\\{\\\\langle\\}", 'g'), "\\\\Big\\\\langle "],
  [new RegExp("\\\\Big \\{\\\\rangle\\}", 'g'), "\\\\Big\\\\rangle "],
  [new RegExp("\\\\Big \\{\\\\langle\\}", 'g'), "\\\\Big\\\\langle "],
  [new RegExp("\\\\Bigr\\{\\\\rangle\\}", 'g'), "\\\\Bigr\\\\rangle "],
  [new RegExp("\\\\Bigr\\{\\\\langle\\}", 'g'), "\\\\Bigr\\\\langle "],
  [new RegExp("\\\\Bigr \\{\\\\rangle\\}", 'g'), "\\\\Bigr\\\\rangle "],
  [new RegExp("\\\\Bigr \\{\\\\langle\\}", 'g'), "\\\\Bigr\\\\langle "],
  [new RegExp("\\\\Bigm\\{\\\\rangle\\}", 'g'), "\\\\Bigm\\\\rangle "],
  [new RegExp("\\\\Bigm\\{\\\\langle\\}", 'g'), "\\\\Bigm\\\\langle "],
  [new RegExp("\\\\Bigm \\{\\\\rangle\\}", 'g'), "\\\\Bigm\\\\rangle "],
  [new RegExp("\\\\Bigm \\{\\\\langle\\}", 'g'), "\\\\Bigm\\\\langle "],
  [new RegExp("\\\\Bigl\\{\\\\rangle\\}", 'g'), "\\\\Bigl\\\\rangle "],
  [new RegExp("\\\\Bigl\\{\\\\langle\\}", 'g'), "\\\\Bigl\\\\langle "],
  [new RegExp("\\\\Bigl \\{\\\\rangle\\}", 'g'), "\\\\Bigl\\\\rangle "],
  [new RegExp("\\\\Bigl \\{\\\\langle\\}", 'g'), "\\\\Bigl\\\\langle "],
  [new RegExp("\\\\Bigg\\{\\\\rangle\\}", 'g'), "\\\\Bigg\\\\rangle "],
  [new RegExp("\\\\Bigg\\{\\\\langle\\}", 'g'), "\\\\Bigg\\\\langle "],
  [new RegExp("\\\\Bigg \\{\\\\rangle\\}", 'g'), "\\\\Bigg\\\\rangle "],
  [new RegExp("\\\\Bigg \\{\\\\langle\\}", 'g'), "\\\\Bigg\\\\langle "],
  [new RegExp("\\\\Biggr\\{\\\\rangle\\}", 'g'), "\\\\Biggr\\\\rangle "],
  [new RegExp("\\\\Biggr\\{\\\\langle\\}", 'g'), "\\\\Biggr\\\\langle "],
  [new RegExp("\\\\Biggr \\{\\\\rangle\\}", 'g'), "\\\\Biggr\\\\rangle "],
  [new RegExp("\\\\Biggr \\{\\\\langle\\}", 'g'), "\\\\Biggr\\\\langle "],
  [new RegExp("\\\\Biggl\\{\\\\rangle\\}", 'g'), "\\\\Biggl\\\\rangle "],
  [new RegExp("\\\\Biggl\\{\\\\langle\\}", 'g'), "\\\\Biggl\\\\langle "],
  [new RegExp("\\\\Biggl \\{\\\\rangle\\}", 'g'), "\\\\Biggl\\\\rangle "],
  [new RegExp("\\\\Biggl \\{\\\\langle\\}", 'g'), "\\\\Biggl\\\\langle "],
  [new RegExp("\\\\bigtimes", 'g'), "\\\\times"],
];

export function tryFixEquationBig(latex: string, debug: boolean = false): string {
  const original = latex;
  let out = latex;
  for (const [pattern, replacement] of REPLACEMENTS) {
    out = out.replace(pattern, replacement);
  }
  if (debug && out !== original) {
    console.log(`Fixed equation big from: ${original} to: ${out}`);
  }
  return out;
}
